# ==========================================
#  ABDUZNIK'S AI PROFILE GENERATOR
#  Current Version: v1.4 (Dynamic Categories)
# ==========================================

function gen-profile {
    param (
        [switch]$ResetSkeleton
    )

    # --- CONFIGURATION ---
    $ToolVersion = "1.4"
    $InstallDir = "$HOME\AI-Gen-Profile"
    $SkeletonFile = "$InstallDir\skeleton.md"
    # ---------------------

    Write-Host "Abduznik AI Profile Gen [v$ToolVersion]" -ForegroundColor Magenta
    
    # 1. Get current username
    $currentUser = gh api user -q ".login"
    if (-not $currentUser) {
        Write-Host "!! Error: Not logged into GitHub CLI. Run 'gh auth login' first." -ForegroundColor Red
        return
    }
    Write-Host "Authenticated as: $currentUser" -ForegroundColor Gray

    # --- PHASE 1: SKELETON MANAGEMENT ---
    
    if ($ResetSkeleton) {
        if (Test-Path $SkeletonFile) { Remove-Item $SkeletonFile }
        Write-Host "  -> Skeleton reset requested." -ForegroundColor Yellow
    }

    if (-not (Test-Path $SkeletonFile)) {
        Write-Host "`n[SETUP] No skeleton found. Creating default..." -ForegroundColor Cyan
        # If no skeleton exists, we try to download the default one or create a basic one
        try {
            # Try to fetch from the repo if we are running the installed version, 
            # but here we'll just write the basic fallback to ensure it works offline/first-time
            $skeletonContent = @"
# Hi, I'm {{USERNAME}}

I build tools and software.

## Tech Stack
(Add your badges here)

---

{{DYNAMIC_PROJECTS}}

---
*Generated by AI-Gen-Profile*
"@
            if (-not (Test-Path $InstallDir)) { New-Item -Type Directory -Path $InstallDir -Force | Out-Null }
            $skeletonContent | Set-Content $SkeletonFile -Encoding UTF8
            Write-Host "  -> Created default skeleton at: $SkeletonFile" -ForegroundColor Green
            Write-Host "  -> TIP: Edit this file to customize your Bio and Tech Stack!" -ForegroundColor Yellow
        } catch {
            Write-Host "  !! Failed to create skeleton." -ForegroundColor Red
            return
        }
    } else {
        Write-Host "  -> Loaded existing skeleton." -ForegroundColor Gray
        $skeletonContent = Get-Content $SkeletonFile -Raw -Encoding UTF8
    }

    # --- PHASE 2: GENERATION ---

    # 3. Fetch Repos
    Write-Host "`n[GENERATING] Fetching repository list..." -ForegroundColor Cyan
    $rawRepos = gh repo list --visibility=public --limit 100 --json name,description,stargazerCount,language --jq '.[]'
    
    if (-not $rawRepos) { Write-Host "No repos found." -ForegroundColor Red; return }

    $repos = $rawRepos | ConvertFrom-Json
    
    # Format for AI
    $repoListString = ""
    foreach ($r in $repos) {
        if ($r.name -eq $currentUser) { continue } # Skip profile repo
        $desc = if ($r.description) { $r.description } else { "No description" }
        $lang = if ($r.language) { $r.language } else { "Generic" }
        $repoListString += "- [$($r.name)] ($lang): $desc (Stars: $($r.stargazerCount))`n"
    }

    Write-Host "  Gemini is analyzing your projects to invent categories..." -ForegroundColor Cyan

    # 4. Prompt for Dynamic Categorization
    $fillPrompt = @"
Task: Analyze these GitHub repositories and group them into 3-6 distinct, descriptive categories based on their tech stack and purpose.
Input Repos:
$repoListString

Instructions:
1. Create categories that make sense for this specific user (e.g., if they have many Obsidian tools, make an "Obsidian" category. If they have many AI tools, make an "AI" category).
2. Sort projects by importance (stars) within categories.
3. IGNORE forked repositories unless they seem significant.

Output: Return a JSON Object with a single key "sections" containing an array of objects.
Format:
{
  "sections": [
    {
      "title": "Category Title (e.g. Embedded Systems)",
      "subtitle": "Optional witty subtitle (e.g. Low-level magic)",
      "markdown_list": "- **[Repo](Link)** - Description\n- **[Repo2](Link)** - Description"
    }
  ]
}
Do not use markdown code blocks in the JSON output.
"@

    # Safe Execution
    $safePrompt = $fillPrompt.Replace('"', '"')
    $aiOutput = cmd /c "gemini ""$safePrompt"" 2>&1"
    
    # Clean Output
    $rawString = $aiOutput | Where-Object { $_ -notmatch "\[STARTUP\]" -and $_ -notmatch "Loaded cached" } | Out-String
    
    # Extract JSON
    if ($rawString -match "(?s)\{.*\}") {
        $cleanJson = $matches[0]
    } else {
        $cleanJson = $rawString
    }
    $cleanJson = $cleanJson -replace '```json', '' -replace '```', ''

    try {
        $data = $cleanJson | ConvertFrom-Json
        
        # 5. Build Dynamic Markdown
        $dynamicMd = ""
        
        if ($data.sections) {
            foreach ($section in $data.sections) {
                $dynamicMd += "## $($section.title)`n"
                if ($section.subtitle) {
                    $dynamicMd += "*$($section.subtitle)*`n"
                }
                $dynamicMd += "`n$($section.markdown_list)`n`n"
            }
        } else {
             Write-Host "  !! JSON missing 'sections' key. Dumping raw:" -ForegroundColor Yellow
             Write-Host $cleanJson
        }

        # 6. Fill the Skeleton
        $finalMd = $skeletonContent
        
        # Username Check
        $finalMd = $finalMd.Replace("{{USERNAME}}", $currentUser)
        
        # Dynamic Injection
        if ($finalMd -match "\{\{DYNAMIC_PROJECTS\}" ) {
            $finalMd = $finalMd.Replace("{{DYNAMIC_PROJECTS}}", $dynamicMd)
        } else {
            # Fallback: If old skeleton, try to append or replace known tags
            Write-Host "  -> Warning: '{{DYNAMIC_PROJECTS}}' tag not found in skeleton. Appending to bottom." -ForegroundColor Yellow
            $finalMd += "`n`n$dynamicMd"
        }
        
        # Cleanup old tags just in case user switched skeletons
        $finalMd = $finalMd -replace "\{\{SECTION_[A-Z]+\}"", ""
        
        # 7. Save
        $outFile = "PROFILE_DRAFT.md"
        $finalMd | Set-Content $outFile -Encoding UTF8
        
        Write-Host "`nSUCCESS! Draft saved to: $outFile" -ForegroundColor Magenta
        Write-Host "Review it, then copy content to your '$currentUser/$currentUser' repository." -ForegroundColor White
        
    } catch {
        Write-Host "Error parsing AI response. Check raw output." -ForegroundColor Red
        Write-Host $cleanJson
    }
}