# ==========================================
#  ABDUZNIK'S AI PROFILE GENERATOR
#  Current Version: v2.5 (PR Workflow)
# ==========================================

function gen-profile {
    param (
        [switch]$ResetSkeleton
    )

    $ToolVersion = "2.5"
    $InstallDir = "$HOME\AI-Gen-Profile"
    $SkeletonFile = "$InstallDir\skeleton.md"

    Write-Host "Abduznik AI Profile Gen [v$ToolVersion]" -ForegroundColor Magenta
    
    $currentUser = gh api user -q ".login"
    if (-not $currentUser) {
        Write-Host "!! Error: Not logged into GitHub CLI. Run 'gh auth login' first." -ForegroundColor Red
        return
    }
    Write-Host "Authenticated as: $currentUser" -ForegroundColor Gray

    # --- PHASE 1: SKELETON MANAGEMENT ---
    
    if ($ResetSkeleton) {
        if (Test-Path $SkeletonFile) { Remove-Item $SkeletonFile }
        Write-Host "  -> Skeleton reset requested." -ForegroundColor Yellow
    }

    if (-not (Test-Path $SkeletonFile)) {
        Write-Host "`n[SETUP] No skeleton found. Creating default..." -ForegroundColor Cyan
        try {
            $skeletonContent = "# Hi, I am {{USERNAME}}`n`nI build tools.`n`n---`n`n{{DYNAMIC_PROJECTS}}`n`n---`n*Generated by AI-Gen-Profile*"
            
            if (-not (Test-Path $InstallDir)) { New-Item -Type Directory -Path $InstallDir -Force | Out-Null }
            $skeletonContent | Set-Content $SkeletonFile -Encoding UTF8
            Write-Host "  -> Created default skeleton at: $SkeletonFile" -ForegroundColor Green
        } catch {
            Write-Host "  !! Failed to create skeleton." -ForegroundColor Red
            return
        }
    } else {
        Write-Host "  -> Loaded existing skeleton." -ForegroundColor Gray
        $skeletonContent = Get-Content $SkeletonFile -Raw -Encoding UTF8
    }

    # --- PHASE 2: GENERATION ---

    Write-Host "`n[GENERATING] Fetching repository list..." -ForegroundColor Cyan
    $rawRepos = gh repo list --visibility=public --limit 100 --json name,description,stargazerCount,primaryLanguage,url --jq '.[]'
    
    if (-not $rawRepos) { Write-Host "No repos found." -ForegroundColor Red; return }

    $repos = $rawRepos | ConvertFrom-Json
    
    $repoLookup = @{}
    foreach ($r in $repos) { $repoLookup[$r.name] = $r }

    $repoListString = ""
    foreach ($r in $repos) {
        if ($r.name -eq $currentUser) { continue }
        $desc = if ($r.description) { $r.description } else { "No description" }
        $lang = if ($r.primaryLanguage.name) { $r.primaryLanguage.name } else { "Generic" }
        $repoListString += "- [$($r.name)] ($lang): $desc (Stars: $($r.stargazerCount))`n"
    }

    Write-Host "  Gemini is analyzing your projects to invent categories..." -ForegroundColor Cyan

    $fillPrompt = "Task: Group these repositories into 3-6 categories. Input: $repoListString Output: Markdown formatted categories. Use ## for titles."

    $aiOutput = cmd /c "gemini ""$fillPrompt"" 2>&1"
    
    $rawString = $aiOutput | Where-Object { $_ -notmatch "\[STARTUP\]" -and $_ -notmatch "Loaded cached" } | Out-String
    
    # Universal Parsing (Try JSON, Fallback to Markdown)
    $cleanJson = $rawString -replace '```json', '' -replace '```', ''
    $dynamicMd = ""

    try {
        $data = $cleanJson | ConvertFrom-Json
        if ($data.sections) {
            foreach ($section in $data.sections) {
                $dynamicMd += "## $($section.title)`n"
                if ($section.subtitle) { $dynamicMd += "*$($section.subtitle)*`n" }
                $dynamicMd += "`n$($section.markdown_list)`n`n"
            }
        } elseif ($data.categories) {
             foreach ($cat in $data.categories) {
                $dynamicMd += "## $($cat.name)`n`n"
                foreach ($repoName in $cat.repositories) {
                    if ($repoLookup.ContainsKey($repoName)) {
                        $r = $repoLookup[$repoName]
                        $desc = if ($r.description) { $r.description } else { "No description" }
                        $dynamicMd += "- **[$($r.name)]($($r.url))** - $desc`n"
                    }
                }
                $dynamicMd += "`n"
             }
        }
    } catch {
        Write-Host "  -> JSON parsing failed, using raw AI output as Markdown..." -ForegroundColor Yellow
        $dynamicMd = $rawString
    }

    $finalMd = $skeletonContent
    $finalMd = $finalMd.Replace("{{USERNAME}}", $currentUser)
    
    if ($finalMd -match "\{\{DYNAMIC_PROJECTS\}\}") {
        $finalMd = $finalMd.Replace("{{DYNAMIC_PROJECTS}}", $dynamicMd)
    } else {
        $finalMd += "`n`n$dynamicMd"
    }
    
    $finalMd = $finalMd -replace "\{\{SECTION_[A-Z]+\}\}", ""
    
    # Save Draft
    $outFile = "$PWD\PROFILE_DRAFT.md"
    $finalMd | Set-Content $outFile -Encoding UTF8
    
    Write-Host "`nSUCCESS! Draft saved to: $outFile" -ForegroundColor Magenta
    
    # --- PHASE 3: PR WORKFLOW ---
    
    Write-Host "`n[REVIEW]" -ForegroundColor Cyan
    $choice = Read-Host "Do you want to open a PR to update your profile? (y/n)"
    
    if ($choice -eq 'y') {
        Write-Host "  -> Setting up Pull Request..." -ForegroundColor Green
        
        $tempDir = [System.IO.Path]::GetTempPath() + "ai_profile_update_" + [Guid]::NewGuid().ToString()
        New-Item -ItemType Directory -Path $tempDir | Out-Null
        
        try {
            # 1. Clone
            Write-Host "  -> Cloning $currentUser/$currentUser..." -ForegroundColor DarkGray
            gh repo clone "$currentUser/$currentUser" "$tempDir" 2>$null
            
            # 2. Setup Branch
            $branchName = "ai-profile-update-" + (Get-Date -Format "yyyyMMdd-HHmm")
            Set-Location $tempDir
            git checkout -b $branchName 2>$null
            
            # 3. Overwrite
            $finalMd | Set-Content "README.md" -Encoding UTF8
            
            # 4. Commit & Push
            git add README.md
            git commit -m "Update profile via AI-Gen-Profile" 2>$null
            git push -u origin $branchName 2>$null
            
            # 5. Create PR
            Write-Host "  -> Opening PR..." -ForegroundColor Green
            gh pr create --title "AI Profile Update" --body "Automated profile update generated by AI-Gen-Profile." --web
            
        } catch {
            Write-Host "  !! Error creating PR: $_" -ForegroundColor Red
        } finally {
            # Return to original dir
            Set-Location $PWD
            Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    } else {
        Write-Host "  -> Skipped. You can manually copy the draft content." -ForegroundColor Gray
    }
}
