# ==========================================
#  ABDUZNIK'S AI PROFILE GENERATOR
#  Current Version: v2.9 (Multi-Model Support)
# ==========================================

function gen-profile {
    param (
        [switch]$ResetSkeleton
    )

    $ToolVersion = "2.9"
    $InstallDir = "$HOME\AI-Gen-Profile"
    $SkeletonFile = "$InstallDir\skeleton.md"

    Write-Host "Abduznik AI Profile Gen [v$ToolVersion]" -ForegroundColor Magenta
    
    $currentUser = gh api user -q ".login"
    if (-not $currentUser) {
        Write-Host "!! Error: Not logged into GitHub CLI. Run 'gh auth login' first." -ForegroundColor Red
        return
    }
    Write-Host "Authenticated as: $currentUser" -ForegroundColor Gray

    # --- PHASE 1: SKELETON MANAGEMENT ---
    
    if ($ResetSkeleton) {
        if (Test-Path $SkeletonFile) { Remove-Item $SkeletonFile }
        Write-Host "  -> Skeleton reset requested." -ForegroundColor Yellow
    }

    if (-not (Test-Path $SkeletonFile)) {
        Write-Host "`n[SETUP] No skeleton found. Creating default..." -ForegroundColor Cyan
        try {
            $skeletonContent = "# Hi, I am {{USERNAME}}`n`nI build tools and software.`n`n## Tech Stack`n![Python](https://img.shields.io/badge/-Python-3776AB?style=flat&logo=python&logoColor=white) ![C](https://img.shields.io/badge/-C-A8B9CC?style=flat&logo=c&logoColor=white) ![JavaScript](https://img.shields.io/badge/-JavaScript-F7DF1E?style=flat&logo=javascript&logoColor=black) ![Raspberry Pi](https://img.shields.io/badge/-Raspberry_Pi-C51A4A?style=flat&logo=Raspberry-Pi&logoColor=white) ![Godot](https://img.shields.io/badge/-Godot-478CBF?style=flat&logo=godot-engine&logoColor=white) ![Obsidian](https://img.shields.io/badge/-Obsidian-483699?style=flat&logo=obsidian&logoColor=white)`n`n---`n`n{{DYNAMIC_PROJECTS}}`n`n---`n*Generated by AI-Gen-Profile*"
            
            if (-not (Test-Path $InstallDir)) { New-Item -Type Directory -Path $InstallDir -Force | Out-Null }
            $skeletonContent | Set-Content $SkeletonFile -Encoding UTF8
            Write-Host "  -> Created default skeleton at: $SkeletonFile" -ForegroundColor Green
        } catch {
            Write-Host "  !! Failed to create skeleton." -ForegroundColor Red
            return
        }
    } else {
        Write-Host "  -> Loaded existing skeleton." -ForegroundColor Gray
        $skeletonContent = Get-Content $SkeletonFile -Raw -Encoding UTF8
    }

    # --- PHASE 2: GENERATION ---

    Write-Host "`n[GENERATING] Fetching repository list..." -ForegroundColor Cyan
    $rawRepos = gh repo list --visibility=public --limit 100 --json name,description,stargazerCount,primaryLanguage,url,isPrivate,isArchived --jq '.[]'
    
    if (-not $rawRepos) { Write-Host "No repos found." -ForegroundColor Red; return }

    $repos = $rawRepos | ConvertFrom-Json
    
    $repoLookup = @{}
    $repoNamesOnly = @()

    foreach ($r in $repos) {
        # Strict Filtering
        if ($r.name -eq $currentUser) { continue }
        if ($r.isPrivate -eq $true) { continue }
        if ($r.isArchived -eq $true) { continue }
        
        # Explicit Junk Blocklist
        if ($r.name -eq "test") { continue }
        if ($r.name -eq "export") { continue }
        if ($r.name -match "^WPy64") { continue }
        if ($r.name -eq "PROFILE_DRAFT.md") { continue }
        if ($r.name -match "\.exe$") { continue }
        if ($r.name -match "^temp") { continue }

        $repoLookup[$r.name] = $r
        
        # We send ONLY names and descriptions to AI to help it categorize
        # We do NOT ask AI for links, because it messes them up.
        $repoNamesOnly += "$($r.name) : $($r.description)"
    }
    
    $repoListString = $repoNamesOnly -join "`n"

    Write-Host "  Gemini is categorizing $($repoLookup.Count) projects..." -ForegroundColor Cyan

    # Priority: Smartest (Gemini 3) -> High Bandwidth (Gemma 3) -> Fallback (Flash)
    $ModelList = @("gemini-3-flash-preview", "gemini-2.5-flash", "gemini-2.5-flash-lite", "gemma-3-27b-it")

    # Prompt: "Just give me the headers and the list of names"
    $fillPrompt = "Task: Group these repositories into 3-6 categories. Input:`n$repoListString`n`nInstructions:`n1. Use '## Category Name' for titles.`n2. Under each title, list the repo names as bullet points: '* RepoName'.`n3. Do NOT add descriptions or links yet.`n4. OUTPUT MARKDOWN ONLY. No conversational text."

    $aiOutput = $null
    $success = $false

    foreach ($model in $ModelList) {
        Write-Host "   -> Attempting with model: $model..." -ForegroundColor DarkGray
        
        try {
            if (Test-Path "/usr/local/bin/gemini") {
                # Docker path
                $currentRun = & /usr/local/bin/gemini $fillPrompt --model $model 2>&1 | Out-String
            } else {
                # Standard path
                $currentRun = & gemini $fillPrompt --model $model 2>&1 | Out-String
            }
        } catch {
            $currentRun = "Error: " + $_.Exception.Message
        }

        # Cleanup Warnings
        if ($currentRun -match "Both GOOGLE_API_KEY and GEMINI_API_KEY are set") {
             $currentRun = $currentRun -replace "Both GOOGLE_API_KEY and GEMINI_API_KEY are set\. Using GOOGLE_API_KEY\.", ""
        }
        $currentRun = $currentRun.Trim()

        # Validation for Profile (Expect Markdown Headers or bullets)
        if ($currentRun -match "##" -or $currentRun -match "\* ") {
             $aiOutput = $currentRun
             $success = $true
             break
        }
        
        # Quota Check
        if ($currentRun -match "429" -or $currentRun -match "exhausted" -or $currentRun -match "Quota") {
            Write-Host "      [!] Quota hit on $model. Pausing 3s..." -ForegroundColor Yellow
            Start-Sleep -Seconds 3
            continue
        }
        # Generic Error
        elseif ($currentRun -match "Error" -or $currentRun -match "Exception") {
             Write-Host "      [DEBUG] $currentRun" -ForegroundColor Red
             Write-Host "      [!] Generic error on $model. Switching..." -ForegroundColor Yellow
             Start-Sleep -Seconds 1
             continue
        }
        else {
             Write-Host "      [!] Invalid output format. Switching..." -ForegroundColor Yellow
             continue
        }
    }

    if (-not $success) {
        Write-Host "`n[CRITICAL ERROR] ALL MODELS EXHAUSTED" -ForegroundColor Red
        return
    }
    
    $rawMd = $aiOutput | Where-Object { $_ -notmatch "\[STARTUP\]" -and $_ -notmatch "Loaded cached" } | Out-String
    $rawMd = $rawMd -replace '```markdown', '' -replace '```', ''

    # --- PHASE 3: THE INJECTOR ---
    # We parse the AI's Markdown and inject the Real Data (Links/Desc) from our Lookup Table.
    
    $lines = $rawMd -split "`n"
    $injectedMd = ""
    
    foreach ($line in $lines) {
        $trimmed = $line.Trim()
        
        # 1. Headers (Keep them)
        if ($trimmed -match "^##") {
            $injectedMd += "$trimmed`n`n"
            continue
        }
        
        # 2. Bullet Points (The Repos)
        # We look for lines starting with * or - and containing a repo name
        $foundRepo = $false
        foreach ($key in $repoLookup.Keys) {
            # Regex to match whole word repo name to avoid partial matches
            if ($trimmed -match "\b$key\b") {
                $r = $repoLookup[$key]
                $desc = if ($r.description) { $r.description } else { "" }
                
                # REBUILD THE LINE entirely using official data
                $injectedMd += "- **[$($r.name)]($($r.url))** - $desc`n"
                $foundRepo = $true
                break
            }
        }
        
        # 3. Skip unknown text (Conversational fluff)
        # If it wasn't a header and we didn't find a repo, we ignore it.
        # This effectively filters out "Here is your profile" text.
    }

    if ([string]::IsNullOrWhiteSpace($injectedMd)) {
         Write-Host "  !! Parsing failed. Fallback to simple list." -ForegroundColor Red
         $injectedMd = "## Projects`n"
         foreach ($key in $repoLookup.Keys) {
             $r = $repoLookup[$key]
             $injectedMd += "- **[$($r.name)]($($r.url))** - $($r.description)`n"
         }
    }

    # --- PHASE 4: ASSEMBLY ---

    $finalMd = $skeletonContent
    $finalMd = $finalMd.Replace("{{USERNAME}}", $currentUser)
    
    if ($finalMd -match "\{\{DYNAMIC_PROJECTS\}\}") {
        $finalMd = $finalMd.Replace("{{DYNAMIC_PROJECTS}}", $injectedMd)
    } else {
        $finalMd += "`n`n$injectedMd"
    }
    
    $finalMd = $finalMd -replace "\{\{SECTION_[A-Z]+\}\}", ""
    
    # Save Draft
    $outFile = "$PWD\PROFILE_DRAFT.md"
    $finalMd | Set-Content $outFile -Encoding UTF8
    
    Write-Host "`nSUCCESS! Draft saved to: $outFile" -ForegroundColor Magenta
    
    # --- PHASE 5: PR WORKFLOW ---
    
    Write-Host "`n[REVIEW]" -ForegroundColor Cyan
    $choice = Read-Host "Do you want to open a PR to update your profile? (y/n)"
    
    if ($choice -eq 'y') {
        Write-Host "  -> Setting up Pull Request..." -ForegroundColor Green
        
        $tempDir = [System.IO.Path]::GetTempPath() + "ai_profile_update_" + [Guid]::NewGuid().ToString()
        New-Item -ItemType Directory -Path $tempDir | Out-Null
        
        try {
            Write-Host "  -> Cloning $currentUser/$currentUser..." -ForegroundColor DarkGray
            gh repo clone "$currentUser/$currentUser" "$tempDir" 2>$null
            
            $branchName = "ai-profile-update-" + (Get-Date -Format "yyyyMMdd-HHmm")
            Set-Location $tempDir
            git checkout -b $branchName 2>$null
            
            $finalMd | Set-Content "README.md" -Encoding UTF8
            
            git add README.md
            git commit -m "Update profile via AI-Gen-Profile" 2>$null
            git push -u origin $branchName 2>$null
            
            Write-Host "  -> Opening PR..." -ForegroundColor Green
            gh pr create --title "AI Profile Update" --body "Automated profile update generated by AI-Gen-Profile." --web
            
        } catch {
            Write-Host "  !! Error creating PR: $_" -ForegroundColor Red
        } finally {
            Set-Location $PWD
            Remove-Item $tempDir -Recurse -Force -ErrorAction SilentlyContinue
        }
    } else {
        Write-Host "  -> Skipped." -ForegroundColor Gray
    }
}
